mendersoftware/mender-cli

- main.go
> main: dummy binary for travis testing

- .travis.yml
> travis: minimal travis file for testing

- main.go
> main: build test

- .travis.yml
> travis: detect if we're tagging, only run deploy steps then

- .travis.yml
> travis: print debug info for testing

- .travis.yml
> travis: print more debug info

- .travis.yml
apparently only global vars are visible when tagging?
> travis: debugging env vars

- .travis.yml
> travis: env var fix

- .travis.yml
> travis: push builds to s3

- .travis.yml
> travis: debug

- .travis.yml
> travis: comment on s3 provider

- .travis.yml
> travis: production s3 bucket

- .travis.yml
- tests/Dockerfile
- tests/build-acceptance
- tests/docker-compose.acceptance.yml
- tests/tests/api.py
- tests/tests/artifact.py
- tests/tests/common.py
- tests/tests/s3.py
- tests/tests/test_artifact.py
- tests/tests/test_login.py
https://tracker.mender.io/browse/MEN-1841
also a small fix for 'login' is stacked on top.
> tests: artifact upload

- .travis.yml
- LIC_FILES_CHKSUM.sha256
- Makefile
- vendor/github.com/pkg/errors/LICENSE
- vendor/github.com/pkg/errors/README.md
- vendor/github.com/pkg/errors/appveyor.yml
- vendor/github.com/pkg/errors/errors.go
- vendor/github.com/pkg/errors/stack.go
- vendor/vendor.json
Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>
> Introduce similar Makefile as mender to ease Jenkins building.

- client/deployments/client.go
Found be goreportcard.com
Signed-off-by: Mirza Krak <mirza.krak@endian.se>
> client: fix typo in uploadArtifact error message

- .travis.yml
Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>
> Make sure all Git branches are available, not just HEAD of the PR.

- tests/build-acceptance
- tests/tests/artifact.py
Signed-off-by: Manuel Zedel <manuel.zedel@northern.tech>
> added generation of testing composition to fix failing acceptance tests

- .gitlab-ci.yml
> Update docker:dind image tag to docker:19.03.5-dind

- client/useradm/client.go
- cmd/login.go
ChangeLog:title
Signed-off-by: Peter Grzybowski <peter@northern.tech>
> MEN-3176 Support for two factor authentication token for login

- cmd/login.go
* was: token is: 2fa-code
Changelog: title
Signed-off-by: Peter Grzybowski <peter@northern.tech>
> Change the name of the two-factor auth option.

- Makefile
The Makefile on the master branch had several errors present, so that:
* make check
* make coverage
* make test
all failed.
This PR fixes all these issues
> Fix all errors in the Makefile

- Makefile
Signed-off-by: Ole Petter <ole.orhagen@northern.tech>
> style(Makefile): Remove extraneous whitespace after pipe

- .gitlab-ci.yml
By using the mendertesting template for the unit test jobs
> QA-221: Migrate code coverage to coveralls

- cmd/login.go
- cmd/root.go
Fixed login with password (if not passed) and better configuration file handling.
**Test case 1: no config file existing, no username given**
```
$ ls ~/.mender-clirc
ls: cannot access '/home/armin/.mender-clirc': No such file or directory
$ ./mender-cli login 
FAILURE: No username set
```
**Test case 2: no config file existing, correct username given**
```
$ ls ~/.mender-clirc
ls: cannot access '/home/armin/.mender-clirc': No such file or directory
$ ./mender-cli login --username user@example.com
Password:************
login successful
```
**Test case 3: no config file existing, incorrect username given**
```
$ ls ~/.mender-clirc
ls: cannot access '/home/armin/.mender-clirc': No such file or directory
$ ./mender-cli login --username user@example.com
Password:************
FAILURE: login …
```
> Fixed login with password and better configuration file handling

- Makefile
Changelog: none
Signed-off-by: Fabio Tranchitella <fabio@tranchitella.eu>
> Fix: gocyclo refactoring and switch to go mod

- client/deployments/client.go
- cmd/artifacts.go
- cmd/artifacts_list.go
This feature adds the ability to list artifacts. There is a detail level argument. 
```
/mender-cli artifacts --help     
Operations on mender artifacts.
Usage:
mender-cli artifacts [command]
Available Commands:
list        List mender artifacts from the Mender server.
upload      Upload mender artifact to the Mender server.
...
./mender-cli artifacts list --help
List mender artifacts from the Mender server.
Usage:
mender-cli artifacts list [flags]
Flags:
-d, --detail int   artifacts list detail level [0..2]
-h, --help         help for list
...
```
**Detail level 0 (default):**
```
/mender-cli artifacts list                  
ID: 26615230-3aa5-40f4-8f88-1922bbf64b91
Name: mender-demo-artifact-2.5.0
Signed: false
Modfied: 2020-10-09 13:30:36.987 +0000 UTC
Size: 2034176
Description: For …
```
> Added `artifacts list` feature

- cmd/login.go
This change adds an interactive prompt to specify the username if not given either with configuration file or command line argument.
```
./mender-cli login --help
Log in to the Mender server (required before other operations).
Usage:
mender-cli login [flags]
Flags:
--2fa-code string   two-factor authentication token
-h, --help              help for login
--password string   password (will prompt if not provided)
--username string   username, format: email (will prompt if not provided)
```
```
./mender-cli login
Username: user    
Password: ****
```
> Username prompt if not provided

- .gitlab-ci.yml
- Makefile
- deb-requirements.txt
+ corresponding clean up
might be a good idea to add the `varcheck` & `deadcode` checks to the static template as well - don't you think @lluiscampos? 
Signed-off-by: Manuel Zedel <manuel.zedel@northern.tech>
> further aligned ci pipeline with template usage

- tests/tests/cli.py
- tests/tests/s3.py
- tests/tests/test_login.py
Signed-off-by: Fabio Tranchitella <fabio@tranchitella.eu>
> MEN-4258: add acceptance test: login with password from STDIN

- .gitignore
- Makefile
- cmd/root.go
- log/log.go
Also log errors, when encountered during generation.
> Fix the auto-completion script generation

- client/deviceconnect/client.go
- cmd/filetransfer.go
- cmd/root.go
- log/log.go
Simple filetransfer implementation
Currently has no tests. I looked into it, but this will be a bit heavier than the current tests, since I saw no easy way of mocking this functionality, and hence we would need a client running. Please tell me if I'm wrong here though. Also, the scope of the ticket was 3sp, which means, I guess there is no time.
> MEN-4323: Add filetransfer upload and download support

- .gitlab-ci.yml
- client/common.go
- client/deployments/client.go
- client/deviceconnect/client.go
- client/useradm/client.go
- cmd/login.go
- cmd/portforward.go
- cmd/portforward_tcp.go
- cmd/portforward_udp.go
- cmd/root.go
- cmd/terminal.go
- cmd/util.go
- go.mod
- vendor/modules.txt
> QA-235: pipeline: Switch to static checks by golangci-lint

- client/deployments/client.go
- cmd/artifact_delete.go
- cmd/artifacts.go
Changelog: New command `mender-cli artifacts delete ID` to delete an
artifact
Signed-off-by: Ruben Schwarz <r.schwarz@sotec.eu>
> New command artifacts delete

- tests/tests/test_artifact.py
chore(tests): Add integration tests for delete artifact command
Signed-off-by: Maciej Tomczuk <maciej.tomczuk@northern.tech>
> chore(tests): Add integration tests for delete artifact command

- client/deviceconnect/client.go
- client/deviceconnect/device.go
- cmd/filetransfer.go
- cmd/portforward.go
- cmd/root.go
- cmd/terminal.go
Ticket: MEN-5428
Changelog: title
Signed-off-by: Fabio Tranchitella <fabio.tranchitella@northern.tech>
> chore: improve auth and device error messages for the troubleshoot commands

- client/common.go
- client/deployments/client.go
- client/deviceconnect/client.go
- client/devices/client.go
- cmd/artifact_delete.go
- cmd/artifact_upload.go
- cmd/artifacts_list.go
- cmd/devices_list.go
- cmd/filetransfer.go
- cmd/portforward.go
- cmd/root.go
- cmd/terminal.go
- cmd/util.go
Ticket: MEN-5660
Signed-off-by: Fabio Tranchitella <fabio.tranchitella@northern.tech>
> feat: add option to specify a JWT or personal access token

- client/deployments/client.go
Proposed by the community from
https://hub.mender.io/t/error-message-not-clear-enough-in-mender-cli-artifacts-upload
Ticket: None
> feat: Add meaningful error message for conflict artifact

- tests/tests/test_devices.py
> Added acceptance test for raw flag in list devices
