- .travis.yml
this is a continuation of https://tracker.mender.io/browse/MEN-1836
introducing arch/os releases via a build matrix. this is somewhat a test PR, not sure how this will work before it's merged.
alternatively, we could just copy/paste arch vs os builds in the travis file, but this seems to be a the canonical use case for a matrix, so I suggest going with it. the downside is that we also mix JOB_TYPE into the matrix, so we have to be careful about what and when we're doing (say, only run future acceptance tests if $GOOS=linux).
@maciejmrowiec @kjaskiewiczz
> travis: build github release builds (per platform) via a build matrix

- .travis.yml
upon tagging, all 3 jobs are ran, but we want to build only if JOB_TYPE = deploy.
add the condition to the 'deploy' step, all providers support it.
net result:
- on a PR, only tests are ran (JOB_TYPE=compile_and_basic_tests);
the 'deploy' job is short-circuited with the $TRAVIS_TAG condition
- on tagging, 'compile_and_basic_tests' is short-circuited; OTOH,
'deploy' jobs run for 2xOS, and 2 binaries are emitted as per the build matrix
> travis: conditional deploy

- .travis.yml
s3 provider can upload only from a folder, so prepare one (also for gh releases).
> travis: introduce build dir for platform builds

- README.md
- cmd/login.go
- cmd/root.go
- cmd/util.go
@estenberg suggested:
- changing wording `s/backend/server` across the board
- adding password prompt explanation
- storing the token in user's homedir by default
so here goes. there is no task attached, these are ninja fixes.
technical note: you can find discussions about how `os/user` will not work for cross-compiled binaries, and people in fact create libraries that work around this. I didn't want to pull those in so instead we tested that the CLI actually works ok on a macos. so, we stick to the stadard lib after all as the info seems to refer to earlier versions of go.
> misc fixes

- .travis.yml
- client/useradm/client.go
- tests/Dockerfile
- tests/docker-compose.acceptance.yml
- tests/run.sh
- tests/tests/cli.py
- tests/tests/docker.py
- tests/tests/test_login.py
this takes care of 2 tasks actually:
https://tracker.mender.io/browse/MEN-1843
https://tracker.mender.io/browse/MEN-1842
this is more of an integration test - real services are used. 
conventions are similar to most acceptance tests, differences:
- docker socket is mounted in the testing container so that commands can be called on peer containers
- the whole 'integration' clone is mounted inside the container too (access to compose files)
- we don't intend to use bravado, just plain requests, so it's not being installed and the setup is simpler
- no 'common' and 'conftest' modules, we'll introduce them as we go (new policy is to keep e.g. fixtures private to tests - they rarely are truly reusable, and cause problems when we do reuse them)
- coverage is not collected yet - not sure we want …
> acceptance tests: setup + 'login' test

- README.md
As this is becoming an external tool we should follow a similar layout on the landing page of the repository (README.md) to our other tools (mender, mender-artifact).
**NOTE** that I added a codecov badge that currently has a broken link We can drop this if there is no plan to add this any time soon.
> update README with an "official" look

- .travis.yml
- Dockerfile
The final container is based on busybox instead of scratch to ease extracting the produced binary.
Signed-off-by: Manuel Zedel <manuel.zedel@northern.tech>
> Added multi stage dockerfile to self-contain builds

- .gitignore
- .gitlab-ci.yml
- Makefile
- README.md
Clean build recipe and publish Mac OS X binary to S3
Add a new target in Makefile that can be used from CI, so that we don't
have two different slightly different ways of building the binary.
Also, disable CGO_ENABLED in all targets while unifying and add binaries
to .gitignore.
> MEN-2895: Clean build recipe and publish Mac OS X binary to S3

- tests/docker-compose.acceptance.yml
Update docker-compose version to 2.1 for acceptance tests to comply with the rest of the integration compose files
> Update docker-compose version to 2.1 for acceptance tests

- .gitlab-ci.yml
Fixes CI hung on Docker images build.
> Update docker:dind image tag to docker:19.03.5-dind

- .gitignore
- Makefile
- README.md
- cmd/artifacts.go
- cmd/root.go
1. Add `Bash` auto-completion functionality. Just easy to add, and nice to have.
2. Add `Zsh` auto-completion functionality.
3. Add Makefile targets for generating and installing the auto-completion scripts.
> Add Bash and Zsh auto-completion functionality

- cmd/root.go
- tests/tests/test_artifact.py
- tests/tests/test_login.py
This makes more sense I think, as we generally want users to default to hosted.
Having to manually enter it every time is also annoying.
Thus only when you want the server to point somewhere else enter the alternative server URI.
A follow up to this would be a configuration file with you username and password I think, so that it could automatically login, and we can skip a whole step when doing stuff with the CLI tool.
> Add: Make the server flag default to hosted Mender

- Makefile
- cmd/root.go
Added some basic versioning information. 
*Note: this has to be build using the makefile*
```
$ make
CGO_ENABLED=0 go build -ldflags "-X github.com/mendersoftware/mender-cli/cmd.Version=ee649ee" 
$ ./mender-cli --version
No configuration file found
mender-cli version ee649ee
$ ./mender-cli login --version
No configuration file found
mender-cli version ee649ee
```
Signed-off-by: Armin Schlegel <armin.schlegel@gmx.de>
> Added basic versioning information

- .gitlab-ci.yml
- Makefile
https://tracker.mender.io/browse/QA-229
- the original problem is of course gone, 
- I took quite a few liberties refactoring it (keeping the makefile targets as similar as possible)
the most important problem was that - both the makefile and gitlab.yml mixed together static testing checks and unit testing, and custom templates with mendertesting templates. generally they were completely out of sync.
Makefile targets are now untangled into smaller ones and used in the ci pipeline wherever possible. you have targets for getting tools (test tools, compile deps), static checks, unit tests, acceptance tests build, run...
there is surely some minimal duplication here and there (or crappy scripting), but that's the best I have...  
TODO: verify the artifact publish stage still works - but …
> QA-229: cleanup pipeline and Makefile

- .gitlab-ci.yml
- Makefile
+ ensure that the binary under test is the same binary that is published
this should just ensure the very basic functionality of the to-be-published binary
Signed-off-by: Manuel Zedel <manuel.zedel@northern.tech>
> added very simple execution tests for mac (& linux)

- cmd/artifact_upload.go
- cmd/artifacts_list.go
- cmd/login.go
- cmd/root.go
- cmd/terminal.go
Previously, the configuration --server flag was only bound to the configuration
file value in the login command.
By moving the viper configuration to the root command, and fetching the value
from viper everywhere, the flag is now properly handled everywhere.
Signed-off-by: Ole Petter <ole.orhagen@northern.tech>
> Fix: Respect the --server flag from config everywhere

- Makefile
- tests/tests/common.py
- tests/tests/test_artifact.py
- tests/tests/test_login.py
* [tests] Correct service name in fixture
This has been wrong for a very long time, but the fixture was not
asserting on the return code, so it went unnoticed.
* [Makefile] Download mender-artifact from new location
* [tests] Replace deprecated yield_fixture with fixture
To clear the warnings printed by pytest. They do the same.
> Test fix and misc clean-ups

- cmd/terminal.go
* MEN-4318: Add --record and --playback to terminal command
Save first a header with some meta-data, and then encode the stream of
bytes from stdout. Only stdout is recorded.
Made the positional argument for `terminal` command optional, as now for
playback we don't need to connect to any device.
Changelog: `mender-cli --record <my-file> terminal <DEVICE-ID>` records
the terminal session into a local file.
Changelog: `mender-cli --playback <my-file> terminal` playbacks the
previously recorded terminal session from a local file.
* MEN-4318: Compress terminal recording file
> MEN-4318: Add --record and --playback to terminal command

- client/common.go
- client/deployments/client.go
- client/devices/client.go
- client/useradm/client.go
- cmd/artifact_upload.go
- cmd/devices.go
- cmd/devices_list.go
- cmd/login.go
- cmd/root.go
- tests/docker-compose.acceptance.yml
- tests/tests/api.py
- tests/tests/crypto.py
- tests/tests/test_devices.py
* New command devices list
Fixed minor details in existing code for coherence. Adding acceptance
tests also.
Changelog: New command `mender-cli devices list` to list all devices
from /devauth/devices endpoint. The amount of detail can be controlled
using cli parameter `-d/--detail`, same as for other commands.
* [http clients code] Refactor common code into common.go
> New command devices list

- .gitlab-ci.yml
- Makefile
- main_test.go
- tests/run.sh
- tests/tests/cli.py
- tests/tests/test_artifact.py
- tests/tests/test_login.py
Namely:
* New TestMain to parse flags and call actual main (inspired in backend
services design).
* New make target to compile the binary with coverage instrumentation.
* Test wrapper to use the instrumented binary on cli calls, creating
unique coverage filenames.
* Extend pipeline to collect and publish the coverage stats.
> QA-256: Collect and publish acceptance tests coverage

- Makefile
- cmd/artifact_upload.go
- cmd/artifacts_list.go
- cmd/login.go
- cmd/root.go
- cmd/terminal.go
- tests/docker-compose.acceptance.yml
- tests/tests/common.py
- tests/tests/test_artifact.py
- tests/tests/test_login.py
Previously, the configuration --server flag was only bound to the configuration
file value in the login command.
By moving the viper configuration to the root command, and fetching the value
from viper everywhere, the flag is now properly handled everywhere.
Signed-off-by: Ole Petter <ole.orhagen@northern.tech>
(cherry picked from commit 6a814cd889b037f04c250b332d8360f53c7739d2)
> Cherry1.6: Fix: Respect the --server flag from config everywhere

- .gitlab-ci.yml
- cmd/artifact_upload.go
- cmd/login.go
- cmd/root.go
- tests/docker-compose.acceptance.yml
- tests/tests/common.py
- tests/tests/test_artifact.py
- tests/tests/test_login.py
Previously, the configuration --server flag was only bound to the configuration
file value in the login command.
By moving the viper configuration to the root command, and fetching the value
from viper everywhere, the flag is now properly handled everywhere.
Signed-off-by: Ole Petter <ole.orhagen@northern.tech>
(cherry picked from commit 6a814cd889b037f04c250b332d8360f53c7739d2)
> Cherry1.5: Fix: Respect the --server flag from config everywhere

- README.md
- cmd/terminal.go
* Give explicit error if DEVICE_ID is missing
* Fail if the playback file does not exist (instead of launching a new
terminal!)
* Improve command description, to explain when DEVICE_ID can be
optional
In addition, fixed a typo in `README`.
> [cmd/terminal] Improve cli interface

- .gitlab-ci.yml
* [pipeline] Remove unnecessary dependency liblzma
This call was actually silently failing with `apt-get: not found`. And
in any case it is not needed for mender-cli.
* [pipeline] Fix acceptance tests
By checking out corresponding branch of integration repo (2.4.x) instead
of master.
Fixes error:
```
Service 'acceptance' depends on service 'storage-proxy' which is undefined.
```
> 1.4.x: pipeline fixes

- .gitlab-ci.yml
Using upstream version (now 1.16) for static checks and unit tests.
> Pipeline: golang version update to 1.16

- client/devices/client.go
- cmd/devices_list.go
Add a new flag to enable raw mode for device list command. This helps if
the output is processed further in scripts, ...
Signed-off-by: Ruben Schwarz <r.schwarz@sotec.eu>
> Raw mode for devices list command

- client/deployments/client.go
- cmd/root.go
Ticket: MEN-5725
Signed-off-by: Alex Miliukov <oleksandr.miliukov@northern.tech>
The change also makes configuration more user friendly by adding protocol automatically. Currently, when `"server": "hosted.mender.io"`, artifact upload fails with 401 `authorization not present in header` error, which is misleading.
> MEN-5725: Small usability and error output improvement

- Makefile
The old URL points to an outdated `mender-artifact` from 2019.
> ci: Update mender-artifact download URL

- tests/Dockerfile
To workaround the issue with openssl 3 upgrade in latest Alpine.
We are working on a plan to upgrade the whole ecosystem, but meanwhile we need to pin these jobs to older Alpine to keep CI running.
Ticket: QA-507
Signed-off-by: Alex Miliukov <oleksandr.miliukov@northern.tech>
> QA-507: ci: pin acceptance tests image to Alpine 3.16

- client/devices/client.go
Printing the list of devices with flag -r was not directed to stdout but stderr.
Ticket: None
> fix: List devices in raw mode not in stdout

- client/deviceconnect/client.go
- cmd/terminal.go
I hit some small snags when trying to redirect `mender-cli terminal`'s output in a script.
> Make terminal behave nice in scripts

- tests/tests/docker.py
The docker-compose started to silently exit with return code 1.
Ticket: None
> test(fix): move to docker compose instead of docker-compose.

- client/deployments/client.go
> fix: Check file format when uploading artifacts

- README.md
So that people don't have to search through the page.
Ticket: none
Changelog: none
> chore: Use #mender-cli in the link to the Downloads page

- client/deployments/client.go
- cmd/artifacts_list.go
- cmd/devices_list.go
Changelog: Use the new paginated API endpoint to list artifacts and add support for pagination to the `artifacts  list` command. Note that this is a breaking change as the current API does not support pagination and will always list all artifacts.
Ticket: MEN-8302
> feat: use paginated endpoint to list artifacts

- .gitlab-ci.yml
Run the job by setting `INSTALL_BREW` to `true` in gitlab.
Ticket: MEN-8332
It's more or less identical to this: https://github.com/mendersoftware/mender-artifact/pull/702
NOTE: mender-cli is not yet in brew,  so this is blocked until mender-cli is merged in  [homebrew-core](https://github.com/Homebrew/homebrew-core/pull/223155)
> ci: add job to install with brew on macos runner

- .gitlab-ci.yml
To make sure we don't break `brew` builds (and thus `brew install` for users) with our PRs.
Ticket: MEN-8331
Changelog: none
> ci: Add a new job for testing brew build

- .gitlab-ci.yml
Because coveralls servers are unreliable
Ticket: QA-1232
> ci: allow coveralls publish to fail
